language: cpp
dist: trusty

addons:
    apt:
        packages:
        - tclsh
        - pkg-config
        - cmake
        - libssl-dev
        - build-essential

matrix:
    include:
        - env: BUILD_TYPE=Debug
        - env: BUILD_TYPE=Release
        - os: osx
          osx_image: xcode7.3
          env: BUILD_TYPE=Debug
          before_install: brew update
          install: brew install openssl gnutls nettle
        - os: osx
          osx_image: xcode7.3
          before_install: brew update
          install: brew install openssl gnutls nettle
          env: BUILD_TYPE=Release
        - os: linux
          compiler: x86_64-w64-mingw32-g++
          addons:
            apt:
              packages:
                - gcc-mingw-w64-base
                - binutils-mingw-w64-x86-64
                - gcc-mingw-w64-x86-64
                - gcc-mingw-w64
                - g++-mingw-w64-x86-64
          before_script:
            - export OPENSSL_VERSION="1_1_0i"
            - wget https://github.com/openssl/openssl/archive/OpenSSL_$OPENSSL_VERSION.tar.gz
            - mkdir openssl && cd openssl
            - tar -xvf ../OpenSSL_$OPENSSL_VERSION.tar.gz --strip-components=1
            - ./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64
            - make
            - cd ..
            - export OPENSSL_ROOT_DIR="$PWD/openssl"
            - export CMAKE_SYSTEM_NAME="Windows"
            - export CC="x86_64-w64-mingw32-gcc"
            - export CXX="x86_64-w64-mingw32-g++"
          env: BUILD_TYPE=Release
script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" -DCMAKE_SYSTEM_NAME="$CMAKE_SYSTEM_NAME"; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];   then cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=/usr/local/opt/openssl; fi
    - make
